language: python
cache: pip
jobs:
  include:
    - stage: "Test in Linux"
      os: linux
      python: "3.8.0"
      language: bash
      script:
        - bash install.sh
        - source activate test-environment
        - python3 -m pytest -v -s
    - stage: "Test in Docker"
      services:
        - docker
      python: "3.8.0"
      script:
        - docker build -t graph-database .
        - docker run -it --rm -v "$PWD":/graph-database graph-database python3 -m pytest -v -s
    - stage: "Test in macOS"
      os: osx
      osx_image: xcode12u
      language: shell
      script:
        - bash install.sh
        - source activate test-environment
        - python3 -m pytest -v -s